### ISSUE TITLE
TypeError: usb.on is not a function

### ISSUE THREAD

**Issue by fillahfirdausyah** [song940/node-escpos#376]
Hello, i'v tried and use example code, and igot error like this

TypeError: usb.on is not a function.

My code :
const escpos = require("escpos");
escpos.USB = require('escpos-usb');

const device = new escpos.USB(1046, 20497);
// const device  = new escpos.RawBT();
// const device  = new escpos.Network('localhost');
// const device  = new escpos.Serial('/dev/usb/lp0');
const printer = new escpos.Printer(device);

console.log(device)

device.open(function (err) {
  printer
    .font("a")
    .align("ct")
    .style("bu")
    .size(1, 1)
    .text("The quick brown fox jumps over the lazy dog")
    .text("敏捷的棕色狐狸跳过懒狗")
    .barcode("1234567", "EAN8")
    .qrimage("https://github.com/song940/node-escpos", function (err) {
      this.cut();
      this.close();
    });
});

**Comment by sam-lex** [comment]
this happens on windows 10
- on linux - ubuntu it's working fine.

if you're in a rush like me, a hacky-temporary workaround would be to go into the `node_modules/escpos-usb/index.js` and comment out `usb.on ...` part.

Then you'll run into another problem, saying `usb.removeAllListeners is not a function`. I commented that part out as well. Then it works ok-ish.

 I had already made an app with electron + express and stuff on Linux about a month ago. And just about 3 days ago I tested on a windows machine for the first time, and got these same errors...
I still got another problem to work with, which is the image I generate for it to print seems to "not fit" all of a sudden..

It seems to be somewhat related with this.. idk https://github.com/MadLittleMods/node-usb-detection/issues/77

Anyways.. good luck

**Comment by romaia** [comment]
This actually seem to be related with a major release of `usb` [1]

From what I checked, this project didn't pin the dependency [2], and it was working fine with version 1.9.2

Using `yarn set resolution usb@npm:* 1.9.2 --save` for now fixed this for me

[1] https://www.npmjs.com/package/usb
[2] https://github.com/song940/node-escpos/blob/v3/packages/usb/package.json#L10

**Comment by fillahfirdausyah** [comment]
> this happens on windows 10
> 
> * on linux - ubuntu it's working fine.
> 
> if you're in a rush like me, a hacky-temporary workaround would be to go into the `node_modules/escpos-usb/index.js` and comment out `usb.on ...` part.
> 
> Then you'll run into another problem, saying `usb.removeAllListeners is not a function`. I commented that part out as well. Then it works ok-ish.
> 
> I had already made an app with electron + express and stuff on Linux about a month ago. And just about 3 days ago I tested on a windows machine for the first time, and got these same errors... I still got another problem to work with, which is the image I generate for it to print seems to "not fit" all of a sudden..
> 
> It seems to be somewhat related with this.. idk [MadLittleMods/node-usb-detection#77](https://github.com/MadLittleMods/node-usb-detection/issues/77)
> 
> Anyways.. good luck

oh wow, for now it's working. thanks

**Comment by peteruithoven** [comment]
For npm using folks:
As of NPM [v8.3](https://github.com/npm/cli/releases/tag/v8.3.0) you can override the version in your package.json by adding an [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) section:
``` json
"overrides": {
  "usb": "^1.9.2"
}
```
For earlier versions we noticed you can also install `usb` as a direct dependency.
```
npm install usb@1.9.2
```

(Using version 1.9.2 as [romaia](https://github.com/romaia) advised)

**Comment by flapili** [comment]
Same issue and using usb@1.9.2 did not help :/

**Comment by AppPilots** [comment]
Same problem here... 
No solution at all.

**Comment by flapili** [comment]
Look like usb@1.9.2 doesn't existe (anymore?)
https://www.npmjs.com/package/usb/v/1.8.8
Using 1.8.8 solved the issue

**Comment by YovanggaAnandhika** [comment]
For Fix The Problem Please Migrate To USB Version 2
@see https://github.com/node-usb/node-usb#migrating-to-v200
@see https://github.com/song940/node-escpos/pull/388

i am change node_module/escpos-usb like 
`
let { usb } = require('usb');
`

Like my pull request. please merger @song940

**Comment by YovanggaAnandhika** [comment]
please close this issue

**Comment by ferminc** [comment]
> go into the `node_modules/escpos-usb/index.js` and comment out `usb.on ...` part.

this worked for me, I also updated to usb 2.5.0, btw yes, this is still an issue

**Comment by Siyavash-Adib** [comment]
> This actually seem to be related with a major release of `usb` [1]
> 
> From what I checked, this project didn't pin the dependency [2], and it was working fine with version 1.9.2
> 
> Using `yarn set resolution usb@npm:* 1.9.2 --save` for now fixed this for me
> 
> [1] https://www.npmjs.com/package/usb [2] https://github.com/song940/node-escpos/blob/v3/packages/usb/package.json#L10

Thank a lot, it's working for me now

**Comment by ferminc** [comment]
I recommend you to use https://github.com/node-escpos/driver
The song940 node-escpos is basically deprecated by now

Sent from my iPhone

On 27 Jun 2023, at 06:36, Siyavash-Adib ***@***.***> wrote:

﻿

This actually seem to be related with a major release of usb [1]

From what I checked, this project didn't pin the dependency [2], and it was working fine with version 1.9.2

Using yarn set resolution ***@***.***:* 1.9.2 --save for now fixed this for me

[1] https://www.npmjs.com/package/usb [2] https://github.com/song940/node-escpos/blob/v3/packages/usb/package.json#L10

Thank a lot, it's working for me now

**Comment by Joshjoyb** [comment]
> this happens on windows 10
> 
> * on linux - ubuntu it's working fine.
> 
> if you're in a rush like me, a hacky-temporary workaround would be to go into the `node_modules/escpos-usb/index.js` and comment out `usb.on ...` part.
> 
> Then you'll run into another problem, saying `usb.removeAllListeners is not a function`. I commented that part out as well. Then it works ok-ish.
> 
> I had already made an app with electron + express and stuff on Linux about a month ago. And just about 3 days ago I tested on a windows machine for the first time, and got these same errors... I still got another problem to work with, which is the image I generate for it to print seems to "not fit" all of a sudden..
> 
> It seems to be somewhat related with this.. idk [MadLittleMods/node-usb-detection#77](https://github.com/MadLittleMods/node-usb-detection/issues/77)
> 
> Anyways.. good luck

After doing this, I'm getting another error message that goes: "LIBUSB_ERROR_NOT_SUPPORTED" - what should I do?

**Comment by sam-lex** [comment]
> After doing this, I'm getting another error message that goes: "LIBUSB_ERROR_NOT_SUPPORTED" - what should I do?

I would recommend you check out this one instead https://github.com/node-escpos/driver or some other solutions from other comments.

I myself am not using it anymore, so I have no idea. But regarding your error `LIBUSB_ERROR_NOT_SUPPORTED`, it's listed in here:
https://github.com/lsongdev/node-escpos/blob/v3/packages/usb/README.md

**Comment by fuadriyadhi** [comment]
Why, when I comment usb.on, an error appears "LIBUSB_ERROR_NOT_SUPPORTED"

**Comment by alstonmendonca** [comment]
@fuadriyadhi , download LinUSB driver installer for Windows. Then download the universal driver for your ESCPOS System.

**Comment by YovanggaAnandhika** [comment]
> [@fuadriyadhi](https://github.com/fuadriyadhi) , download LinUSB driver installer for Windows. Then download the universal driver for your ESCPOS System.

i recommendation apps for windows [Zadig](https://zadig.akeo.ie/). you can select mode driver. more advances and portable

**Comment by fuadriyadhi** [comment]
what if usb ieee 1284 is nothing to replace in zadig, how should i do?
